### ISSUE TITLE
not block popup (NSFW)

### ISSUE THREAD

**Issue by wernser412** [schomery/popup-blocker#111]
1. enter `https://hentaifox.com/`
2. I get popup when entering to read.

preview: 
[sample.zip](https://github.com/schomery/popup-blocker/files/5060592/sample.zip)

when it blocks the popup it automatically redirects me to:

`https://thebestgame2020.com/ts/ts_0620/land_ts_250620_en/?utm_campaign=pu_directbuy_hentaifox.com&utm_content=hentaifox.com&bnid=land_ts_250620_en&land=land_ts_250620_en&crID=2478512&zID=504`

It should redirect me to a page with the same domain.

**Comment by schomery** [comment]
It seems like the extension has successfully blocked the popup, and the script that is responsible for displaying the popup redirects you to the popup instead of allowing you to visit the content. If this is the case, try to enable the "Prevent page redirection for 2 seconds after a popup is requested" option.

**Comment by wernser412** [comment]
I already enabled it but the same thing happens, it directs me to another page. use Popup Blocker (strict)
0.5.3

**Comment by wernser412** [comment]
@schomery when I click on the image, I get the popup
