### ISSUE TITLE
youtube live chat issue on Firefox

### ISSUE THREAD

**Issue by schomery** [schomery/popup-blocker#44]
Live chat link: https://www.youtube.com/watch?v=65Jwe9hrqvA

Minimal WebExtension: [example.zip](https://github.com/schomery/popup-blocker/files/1210510/example.zip)

Error: `TypeError: this._origDispatchEvent is undefined`

**Comment by schomery** [comment]
@tophf I would appreciate if you can take a look at this bug. There is a minimal content script code that causes an error in the YouTube's live chat in Firefox browser (there is no custom element support in FF yet). Do you have any idea what is going wrong?

**Comment by tophf** [comment]
Hmm, I can reproduce it in FF55 but not in FF57 so I guess it's just another legacy/single-process bug.

**Comment by schomery** [comment]
I am getting the same error even in FF 57.0a1. I think I am somehow messing up the function's scope with this overwrite.

**Comment by tophf** [comment]
I meant FF57 in multi-process mode is working fine. I don't know the official roadmap for enforcing it, but personally I consider it the only sane mode.

As for your code, it's localized to the block scope, and there's nothing particularly wrong AFAICT. Just another FF bug, which you'll have to circumvent by excluding youtube or maybe by using straight reassignment of Node.prototype.dispatchEvent instead of defining a property.

**Comment by Freduser9** [comment]
@schomery 
I'm also having problems with YouTube Live chat.

In YouTube Live, it's not possible to close the chat after reopening it.

To reproduce the problem, do the following:

1. Start a live stream on YouTube.

2. Close the live chat and reopen it. Then try closing it again...

I'm using Firefox version 150.

**Comment by Freduser9** [comment]
The bug also occurs in Chrome.
