### ISSUE TITLE
0.5.0 release

### ISSUE THREAD

**Issue by schomery** [schomery/popup-blocker#77]
General note: This is a major release. Almost all the blocker code is rewritten. 

@narcolepticinsomniac I would appreciate if you can test this new implementation on a few websites and report back.

**Comment by narcolepticinsomniac** [comment]
For sure. 

One big issue that seems to be resolved in the update is `target="_blank"` links. In Chromium at least, they've been flaky for a while. Sometimes whitelisted sites would still get blocked, and you'd need to reload the page. A lot of times if they were blocked, clicking it multiple times, one would slip through. If they were blocked, right clicking to open manually would sometimes also trigger it to open, or if you actually clicked the context-menu, two would open.

All of these issues seem better. I never bothered reporting because they were hard to repro consistently, and you seemed busy with other stuff.

In general, lately I have less go-to sites that are always terrible with popups, but I'll keep the new version installed and seek them out.

Found a couple little bugs so far, but I don't think they're anything new having to do with the update. 

Screen records and URLs:

[Videos.zip](https://github.com/schomery/popup-blocker/files/2284632/Videos.zip)

**Comment by smed79** [comment]
@narcolepticinsomniac Warn about **NSFW** content next time (Please).

**Comment by schomery** [comment]
I guess they use google.com to test if there is a popup blocker installed!

Please update to the latest dev version and let me know if you still get these popups.

**Comment by narcolepticinsomniac** [comment]
>I guess they use google.com to test if there is a popup blocker installed!

Must be. Hadn't occurred to me at the time, but IIRC `google.com` is whitelisted by default, which is probably common in popup blockers, so maybe they exploit that to try to slip one by, or run some check. I don't really wanna blacklist google though, that sounds like a PITA.

The other example is fixed, thanks. So far, so good. All the changes I've seen have been positive.

**Comment by narcolepticinsomniac** [comment]
Yeah, it's because they're whitelisted by default since they open a google page. If you remove google from the whitelist, they're blocked. Blacklisting google would probably be annoying though, so maybe you could just backlist the URL if a lot of popup scripts are using that particular URL.

**Comment by schomery** [comment]
I cannot think of any way to block this without having google.com removed from the list.

**Comment by smed79** [comment]
@narcolepticinsomniac As custom filter, add to your adblock ([ABP](https://adblockplus.org/), AdB, [uBo](https://github.com/gorhill/uBlock#installation)...) :
```
||google.com/favicon.ico$popup,third-party
```

**Comment by narcolepticinsomniac** [comment]
>add to your adblock

Already did, but I appreciate it. I was suggesting he might wanna do something about them in PBS, because popup scripts seem to be exploiting google favicon URLs since they know they'll be whitelisted. If not, NBD, but users won't understand why these weird popups are getting through, they'll just think it's the blocker's fault.

**Comment by pizzadude** [comment]
@schomery when will 0.5.0.x be released on the AMO?

**Comment by schomery** [comment]
@pizzadude new new release works fine on FF as far as I can tell. I am still waiting for #80.

**Comment by schomery** [comment]
Looks like the 0.5.0.x release is stable. I just released the FF version too. Thanks all for the reports and contributions.

**Comment by narcolepticinsomniac** [comment]
Sent you an email.
