### ISSUE TITLE
Firefox add-on page appears to lack proper privacy policy

### ISSUE THREAD

**Issue by jkarlsso** [schomery/popup-blocker#95]
I was unable to find a proper privacy policy navigating from Firefox add-on page.
(Using Firefox on Android)

The privacy policy link only mentions privacy regarding one specific setting and lacks a link to additional information.

I also searched:
add-on overview
FAQ page
Main home page front
GitHub project front
GitHub readme.md

Please update with more complete information or let me know if I have missed something (I often experience problems with Firefox's find-in-page) and close the the issue.

**Comment by schomery** [comment]
There is no privacy info since this extension does not collect any data, nor it sends or receives anything from any server (if WOT is enabled, then the popup URL is sent to WOT to decide whether this is a legit domain or not. This feature is opt-in). Do you want me to add this to all of these pages? If so, please reopen.
